- hosts: all
  become: true

  vars:
    pip_install_packages:
      - name: docker

  roles:
    - geerlingguy.pip
    - geerlingguy.docker

  tasks:
    - name: Create Redmine env file
      ansible.builtin.template:
        src: templates/redmine.env.j2
        dest: /home/{{ ansible_user }}/redmine.env
        mode: '0644'
      tags:
        - deploy

    - name: Run Redmine container
      community.docker.docker_container:
        name: redmine
        image: "{{ redmine_image }}"
        state: started
        restart_policy: always
        ports:
          - "{{ redmine_port }}:3000"
        env_file: /home/{{ ansible_user }}/redmine.env
      tags:
        - deploy
